kind = "web"
previewPath = "/"
title = "Khang Chinese Restaurant & Dimsum"
version = "1.0.0"
id = "artifacts/khang"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22468

[services.development]
run = "pnpm --filter @workspace/khang run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/khang", "run", "build" ]
publicDir = "artifacts/khang/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22468"
BASE_PATH = "/"
